name: Build

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x

      - name: Build
        run: yarn build

      - name: Commit built files
        if: github.event_name == 'push'
        run:  |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add dist
          git commit -m "Automatic build" && git push || true
